//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Comisariato.Ride.Retencion {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("RetencionEncabezado")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class RetencionEncabezado : global::System.Data.DataSet {
        
        private EncabezadoOrdenGiroDataTable tableEncabezadoOrdenGiro;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public RetencionEncabezado() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected RetencionEncabezado(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["EncabezadoOrdenGiro"] != null)) {
                    base.Tables.Add(new EncabezadoOrdenGiroDataTable(ds.Tables["EncabezadoOrdenGiro"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public EncabezadoOrdenGiroDataTable EncabezadoOrdenGiro {
            get {
                return this.tableEncabezadoOrdenGiro;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            RetencionEncabezado cln = ((RetencionEncabezado)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["EncabezadoOrdenGiro"] != null)) {
                    base.Tables.Add(new EncabezadoOrdenGiroDataTable(ds.Tables["EncabezadoOrdenGiro"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableEncabezadoOrdenGiro = ((EncabezadoOrdenGiroDataTable)(base.Tables["EncabezadoOrdenGiro"]));
            if ((initTable == true)) {
                if ((this.tableEncabezadoOrdenGiro != null)) {
                    this.tableEncabezadoOrdenGiro.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "RetencionEncabezado";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/RetencionEncabezado.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableEncabezadoOrdenGiro = new EncabezadoOrdenGiroDataTable();
            base.Tables.Add(this.tableEncabezadoOrdenGiro);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeEncabezadoOrdenGiro() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            RetencionEncabezado ds = new RetencionEncabezado();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void EncabezadoOrdenGiroRowChangeEventHandler(object sender, EncabezadoOrdenGiroRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class EncabezadoOrdenGiroDataTable : global::System.Data.TypedTableBase<EncabezadoOrdenGiroRow> {
            
            private global::System.Data.DataColumn columnIDTIPODOCUMENTO;
            
            private global::System.Data.DataColumn columnSERIE2PROVEEDOR;
            
            private global::System.Data.DataColumn columnSERIE1PROVEEDOR;
            
            private global::System.Data.DataColumn columnNUMERODOCUMENTOPROVEEDOR;
            
            private global::System.Data.DataColumn columnSERIE1RETENCION;
            
            private global::System.Data.DataColumn columnSERIE2RETENCION;
            
            private global::System.Data.DataColumn columnNUMERORETECION;
            
            private global::System.Data.DataColumn columnFechaRetencion;
            
            private global::System.Data.DataColumn columnIdentificacionProveedor;
            
            private global::System.Data.DataColumn columnRazonSocialProveedor;
            
            private global::System.Data.DataColumn columnRUC;
            
            private global::System.Data.DataColumn columnNOMBRECOMERCIAL;
            
            private global::System.Data.DataColumn columnRazonSocialComercial;
            
            private global::System.Data.DataColumn columnDireccionComercial;
            
            private global::System.Data.DataColumn columnLogoEmpresa;
            
            private global::System.Data.DataColumn columnIDORDENGIRO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public EncabezadoOrdenGiroDataTable() {
                this.TableName = "EncabezadoOrdenGiro";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal EncabezadoOrdenGiroDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected EncabezadoOrdenGiroDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IDTIPODOCUMENTOColumn {
                get {
                    return this.columnIDTIPODOCUMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SERIE2PROVEEDORColumn {
                get {
                    return this.columnSERIE2PROVEEDOR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SERIE1PROVEEDORColumn {
                get {
                    return this.columnSERIE1PROVEEDOR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NUMERODOCUMENTOPROVEEDORColumn {
                get {
                    return this.columnNUMERODOCUMENTOPROVEEDOR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SERIE1RETENCIONColumn {
                get {
                    return this.columnSERIE1RETENCION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SERIE2RETENCIONColumn {
                get {
                    return this.columnSERIE2RETENCION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NUMERORETECIONColumn {
                get {
                    return this.columnNUMERORETECION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FechaRetencionColumn {
                get {
                    return this.columnFechaRetencion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdentificacionProveedorColumn {
                get {
                    return this.columnIdentificacionProveedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RazonSocialProveedorColumn {
                get {
                    return this.columnRazonSocialProveedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RUCColumn {
                get {
                    return this.columnRUC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NOMBRECOMERCIALColumn {
                get {
                    return this.columnNOMBRECOMERCIAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RazonSocialComercialColumn {
                get {
                    return this.columnRazonSocialComercial;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DireccionComercialColumn {
                get {
                    return this.columnDireccionComercial;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn LogoEmpresaColumn {
                get {
                    return this.columnLogoEmpresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IDORDENGIROColumn {
                get {
                    return this.columnIDORDENGIRO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public EncabezadoOrdenGiroRow this[int index] {
                get {
                    return ((EncabezadoOrdenGiroRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event EncabezadoOrdenGiroRowChangeEventHandler EncabezadoOrdenGiroRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event EncabezadoOrdenGiroRowChangeEventHandler EncabezadoOrdenGiroRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event EncabezadoOrdenGiroRowChangeEventHandler EncabezadoOrdenGiroRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event EncabezadoOrdenGiroRowChangeEventHandler EncabezadoOrdenGiroRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddEncabezadoOrdenGiroRow(EncabezadoOrdenGiroRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public EncabezadoOrdenGiroRow AddEncabezadoOrdenGiroRow(
                        string IDTIPODOCUMENTO, 
                        string SERIE2PROVEEDOR, 
                        string SERIE1PROVEEDOR, 
                        string NUMERODOCUMENTOPROVEEDOR, 
                        string SERIE1RETENCION, 
                        string SERIE2RETENCION, 
                        string NUMERORETECION, 
                        string FechaRetencion, 
                        string IdentificacionProveedor, 
                        string RazonSocialProveedor, 
                        string RUC, 
                        string NOMBRECOMERCIAL, 
                        string RazonSocialComercial, 
                        string DireccionComercial, 
                        byte[] LogoEmpresa, 
                        string IDORDENGIRO) {
                EncabezadoOrdenGiroRow rowEncabezadoOrdenGiroRow = ((EncabezadoOrdenGiroRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IDTIPODOCUMENTO,
                        SERIE2PROVEEDOR,
                        SERIE1PROVEEDOR,
                        NUMERODOCUMENTOPROVEEDOR,
                        SERIE1RETENCION,
                        SERIE2RETENCION,
                        NUMERORETECION,
                        FechaRetencion,
                        IdentificacionProveedor,
                        RazonSocialProveedor,
                        RUC,
                        NOMBRECOMERCIAL,
                        RazonSocialComercial,
                        DireccionComercial,
                        LogoEmpresa,
                        IDORDENGIRO};
                rowEncabezadoOrdenGiroRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowEncabezadoOrdenGiroRow);
                return rowEncabezadoOrdenGiroRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                EncabezadoOrdenGiroDataTable cln = ((EncabezadoOrdenGiroDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new EncabezadoOrdenGiroDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnIDTIPODOCUMENTO = base.Columns["IDTIPODOCUMENTO"];
                this.columnSERIE2PROVEEDOR = base.Columns["SERIE2PROVEEDOR"];
                this.columnSERIE1PROVEEDOR = base.Columns["SERIE1PROVEEDOR"];
                this.columnNUMERODOCUMENTOPROVEEDOR = base.Columns["NUMERODOCUMENTOPROVEEDOR"];
                this.columnSERIE1RETENCION = base.Columns["SERIE1RETENCION"];
                this.columnSERIE2RETENCION = base.Columns["SERIE2RETENCION"];
                this.columnNUMERORETECION = base.Columns["NUMERORETECION"];
                this.columnFechaRetencion = base.Columns["FechaRetencion"];
                this.columnIdentificacionProveedor = base.Columns["IdentificacionProveedor"];
                this.columnRazonSocialProveedor = base.Columns["RazonSocialProveedor"];
                this.columnRUC = base.Columns["RUC"];
                this.columnNOMBRECOMERCIAL = base.Columns["NOMBRECOMERCIAL"];
                this.columnRazonSocialComercial = base.Columns["RazonSocialComercial"];
                this.columnDireccionComercial = base.Columns["DireccionComercial"];
                this.columnLogoEmpresa = base.Columns["LogoEmpresa"];
                this.columnIDORDENGIRO = base.Columns["IDORDENGIRO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnIDTIPODOCUMENTO = new global::System.Data.DataColumn("IDTIPODOCUMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDTIPODOCUMENTO);
                this.columnSERIE2PROVEEDOR = new global::System.Data.DataColumn("SERIE2PROVEEDOR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSERIE2PROVEEDOR);
                this.columnSERIE1PROVEEDOR = new global::System.Data.DataColumn("SERIE1PROVEEDOR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSERIE1PROVEEDOR);
                this.columnNUMERODOCUMENTOPROVEEDOR = new global::System.Data.DataColumn("NUMERODOCUMENTOPROVEEDOR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNUMERODOCUMENTOPROVEEDOR);
                this.columnSERIE1RETENCION = new global::System.Data.DataColumn("SERIE1RETENCION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSERIE1RETENCION);
                this.columnSERIE2RETENCION = new global::System.Data.DataColumn("SERIE2RETENCION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSERIE2RETENCION);
                this.columnNUMERORETECION = new global::System.Data.DataColumn("NUMERORETECION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNUMERORETECION);
                this.columnFechaRetencion = new global::System.Data.DataColumn("FechaRetencion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFechaRetencion);
                this.columnIdentificacionProveedor = new global::System.Data.DataColumn("IdentificacionProveedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdentificacionProveedor);
                this.columnRazonSocialProveedor = new global::System.Data.DataColumn("RazonSocialProveedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRazonSocialProveedor);
                this.columnRUC = new global::System.Data.DataColumn("RUC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRUC);
                this.columnNOMBRECOMERCIAL = new global::System.Data.DataColumn("NOMBRECOMERCIAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOMBRECOMERCIAL);
                this.columnRazonSocialComercial = new global::System.Data.DataColumn("RazonSocialComercial", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRazonSocialComercial);
                this.columnDireccionComercial = new global::System.Data.DataColumn("DireccionComercial", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDireccionComercial);
                this.columnLogoEmpresa = new global::System.Data.DataColumn("LogoEmpresa", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLogoEmpresa);
                this.columnIDORDENGIRO = new global::System.Data.DataColumn("IDORDENGIRO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDORDENGIRO);
                this.columnIDTIPODOCUMENTO.MaxLength = 20;
                this.columnSERIE2PROVEEDOR.MaxLength = 3;
                this.columnSERIE1PROVEEDOR.MaxLength = 3;
                this.columnNUMERODOCUMENTOPROVEEDOR.MaxLength = 9;
                this.columnSERIE1RETENCION.MaxLength = 3;
                this.columnSERIE2RETENCION.MaxLength = 3;
                this.columnNUMERORETECION.MaxLength = 9;
                this.columnFechaRetencion.MaxLength = 20;
                this.columnIdentificacionProveedor.MaxLength = 20;
                this.columnRazonSocialProveedor.MaxLength = 900;
                this.columnRUC.MaxLength = 20;
                this.columnNOMBRECOMERCIAL.MaxLength = 900;
                this.columnRazonSocialComercial.MaxLength = 900;
                this.columnDireccionComercial.MaxLength = 800;
                this.columnIDORDENGIRO.MaxLength = 20;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public EncabezadoOrdenGiroRow NewEncabezadoOrdenGiroRow() {
                return ((EncabezadoOrdenGiroRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new EncabezadoOrdenGiroRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(EncabezadoOrdenGiroRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.EncabezadoOrdenGiroRowChanged != null)) {
                    this.EncabezadoOrdenGiroRowChanged(this, new EncabezadoOrdenGiroRowChangeEvent(((EncabezadoOrdenGiroRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.EncabezadoOrdenGiroRowChanging != null)) {
                    this.EncabezadoOrdenGiroRowChanging(this, new EncabezadoOrdenGiroRowChangeEvent(((EncabezadoOrdenGiroRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.EncabezadoOrdenGiroRowDeleted != null)) {
                    this.EncabezadoOrdenGiroRowDeleted(this, new EncabezadoOrdenGiroRowChangeEvent(((EncabezadoOrdenGiroRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.EncabezadoOrdenGiroRowDeleting != null)) {
                    this.EncabezadoOrdenGiroRowDeleting(this, new EncabezadoOrdenGiroRowChangeEvent(((EncabezadoOrdenGiroRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveEncabezadoOrdenGiroRow(EncabezadoOrdenGiroRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                RetencionEncabezado ds = new RetencionEncabezado();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "EncabezadoOrdenGiroDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class EncabezadoOrdenGiroRow : global::System.Data.DataRow {
            
            private EncabezadoOrdenGiroDataTable tableEncabezadoOrdenGiro;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal EncabezadoOrdenGiroRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableEncabezadoOrdenGiro = ((EncabezadoOrdenGiroDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IDTIPODOCUMENTO {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.IDTIPODOCUMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IDTIPODOCUMENTO\' de la tabla \'EncabezadoOrdenGiro\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.IDTIPODOCUMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SERIE2PROVEEDOR {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.SERIE2PROVEEDORColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'SERIE2PROVEEDOR\' de la tabla \'EncabezadoOrdenGiro\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.SERIE2PROVEEDORColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SERIE1PROVEEDOR {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.SERIE1PROVEEDORColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'SERIE1PROVEEDOR\' de la tabla \'EncabezadoOrdenGiro\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.SERIE1PROVEEDORColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NUMERODOCUMENTOPROVEEDOR {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.NUMERODOCUMENTOPROVEEDORColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'NUMERODOCUMENTOPROVEEDOR\' de la tabla \'EncabezadoOrdenGir" +
                                "o\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.NUMERODOCUMENTOPROVEEDORColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SERIE1RETENCION {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.SERIE1RETENCIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'SERIE1RETENCION\' de la tabla \'EncabezadoOrdenGiro\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.SERIE1RETENCIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SERIE2RETENCION {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.SERIE2RETENCIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'SERIE2RETENCION\' de la tabla \'EncabezadoOrdenGiro\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.SERIE2RETENCIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NUMERORETECION {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.NUMERORETECIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'NUMERORETECION\' de la tabla \'EncabezadoOrdenGiro\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.NUMERORETECIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FechaRetencion {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.FechaRetencionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'FechaRetencion\' de la tabla \'EncabezadoOrdenGiro\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.FechaRetencionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IdentificacionProveedor {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.IdentificacionProveedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IdentificacionProveedor\' de la tabla \'EncabezadoOrdenGiro" +
                                "\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.IdentificacionProveedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string RazonSocialProveedor {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.RazonSocialProveedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'RazonSocialProveedor\' de la tabla \'EncabezadoOrdenGiro\' e" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.RazonSocialProveedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string RUC {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.RUCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'RUC\' de la tabla \'EncabezadoOrdenGiro\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.RUCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NOMBRECOMERCIAL {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.NOMBRECOMERCIALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'NOMBRECOMERCIAL\' de la tabla \'EncabezadoOrdenGiro\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.NOMBRECOMERCIALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string RazonSocialComercial {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.RazonSocialComercialColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'RazonSocialComercial\' de la tabla \'EncabezadoOrdenGiro\' e" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.RazonSocialComercialColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DireccionComercial {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.DireccionComercialColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DireccionComercial\' de la tabla \'EncabezadoOrdenGiro\' es " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.DireccionComercialColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] LogoEmpresa {
                get {
                    try {
                        return ((byte[])(this[this.tableEncabezadoOrdenGiro.LogoEmpresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'LogoEmpresa\' de la tabla \'EncabezadoOrdenGiro\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.LogoEmpresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IDORDENGIRO {
                get {
                    try {
                        return ((string)(this[this.tableEncabezadoOrdenGiro.IDORDENGIROColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IDORDENGIRO\' de la tabla \'EncabezadoOrdenGiro\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableEncabezadoOrdenGiro.IDORDENGIROColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIDTIPODOCUMENTONull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.IDTIPODOCUMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIDTIPODOCUMENTONull() {
                this[this.tableEncabezadoOrdenGiro.IDTIPODOCUMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSERIE2PROVEEDORNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.SERIE2PROVEEDORColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSERIE2PROVEEDORNull() {
                this[this.tableEncabezadoOrdenGiro.SERIE2PROVEEDORColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSERIE1PROVEEDORNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.SERIE1PROVEEDORColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSERIE1PROVEEDORNull() {
                this[this.tableEncabezadoOrdenGiro.SERIE1PROVEEDORColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNUMERODOCUMENTOPROVEEDORNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.NUMERODOCUMENTOPROVEEDORColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNUMERODOCUMENTOPROVEEDORNull() {
                this[this.tableEncabezadoOrdenGiro.NUMERODOCUMENTOPROVEEDORColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSERIE1RETENCIONNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.SERIE1RETENCIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSERIE1RETENCIONNull() {
                this[this.tableEncabezadoOrdenGiro.SERIE1RETENCIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSERIE2RETENCIONNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.SERIE2RETENCIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSERIE2RETENCIONNull() {
                this[this.tableEncabezadoOrdenGiro.SERIE2RETENCIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNUMERORETECIONNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.NUMERORETECIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNUMERORETECIONNull() {
                this[this.tableEncabezadoOrdenGiro.NUMERORETECIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFechaRetencionNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.FechaRetencionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFechaRetencionNull() {
                this[this.tableEncabezadoOrdenGiro.FechaRetencionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIdentificacionProveedorNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.IdentificacionProveedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIdentificacionProveedorNull() {
                this[this.tableEncabezadoOrdenGiro.IdentificacionProveedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRazonSocialProveedorNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.RazonSocialProveedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRazonSocialProveedorNull() {
                this[this.tableEncabezadoOrdenGiro.RazonSocialProveedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRUCNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.RUCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRUCNull() {
                this[this.tableEncabezadoOrdenGiro.RUCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNOMBRECOMERCIALNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.NOMBRECOMERCIALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNOMBRECOMERCIALNull() {
                this[this.tableEncabezadoOrdenGiro.NOMBRECOMERCIALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRazonSocialComercialNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.RazonSocialComercialColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRazonSocialComercialNull() {
                this[this.tableEncabezadoOrdenGiro.RazonSocialComercialColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDireccionComercialNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.DireccionComercialColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDireccionComercialNull() {
                this[this.tableEncabezadoOrdenGiro.DireccionComercialColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsLogoEmpresaNull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.LogoEmpresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetLogoEmpresaNull() {
                this[this.tableEncabezadoOrdenGiro.LogoEmpresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIDORDENGIRONull() {
                return this.IsNull(this.tableEncabezadoOrdenGiro.IDORDENGIROColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIDORDENGIRONull() {
                this[this.tableEncabezadoOrdenGiro.IDORDENGIROColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class EncabezadoOrdenGiroRowChangeEvent : global::System.EventArgs {
            
            private EncabezadoOrdenGiroRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public EncabezadoOrdenGiroRowChangeEvent(EncabezadoOrdenGiroRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public EncabezadoOrdenGiroRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591